--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 26-12-19 8:38:07 PM
-- Server version: 8.0.16
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE nestnx;

--
-- Drop table `celebrities`
--
DROP TABLE IF EXISTS celebrities;

--
-- Drop table `endorsement`
--
DROP TABLE IF EXISTS endorsement;

--
-- Set default database
--
USE nestnx;

--
-- Create table `endorsement`
--
CREATE TABLE endorsement (
  id int(3) NOT NULL AUTO_INCREMENT,
  celebrity_id int(3) DEFAULT NULL,
  name varchar(50) DEFAULT NULL,
  company_name varchar(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `celebrities`
--
CREATE TABLE celebrities (
  id int(3) NOT NULL AUTO_INCREMENT,
  name varchar(50) DEFAULT NULL,
  age int(3) DEFAULT NULL,
  gender varchar(10) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table endorsement
--
INSERT INTO endorsement VALUES
(1, 1, 'Vistara airlines', 'Vistara airlines'),
(2, 1, 'Goibibo', 'Goibibo Travelogics Limited'),
(3, 1, 'Oppo', 'Oppo Mobiles LLC'),
(4, 1, 'Axis Bank', 'Axis Bank'),
(5, 1, 'Lux', 'Lux Cosmetics'),
(6, 1, 'Tanishq', 'TBZ Jewllers Pvt. Ltd'),
(7, 1, 'Royale Atmos', 'Royale Atmos'),
(8, 1, 'Jaquar Lighting ', 'JSX Home Decor '),
(9, 2, 'Reebok', 'Reebok Sports and Fitness'),
(10, 2, 'Exide', 'Exide Batteries'),
(11, 2, 'TVS Motors', 'TVS Motors India Pvt. Ltd.'),
(12, 2, 'Orient Fans', 'Orient Fans'),
(13, 2, 'Aircel', 'Aircel Mobiles Pvt. Ltd'),
(14, 2, 'Bharat Petroleum', 'Bharat Petroleum'),
(15, 2, 'Snickers', 'Perfetti Confesionaries'),
(16, 2, 'Indian Terrain', 'Indian Terrain Limited'),
(17, 2, 'redBus', 'RedBus Online LLC'),
(18, 2, 'Colgate', 'Colgate India Limited'),
(19, 2, 'Mastercard', 'Master Card International'),
(20, 2, 'Bharat Matrimony', 'Bharat Matrimony Pvt. Limited'),
(21, 2, 'GoDaddy', 'GoDaddy Hosting and Online Services'),
(22, 2, 'Indigo Paints', 'Indigo Paints Limited'),
(23, 2, 'NetMeds (online pharmacy)', 'NetMeds Online'),
(24, 2, 'Sumadhura Group', 'Sumadhura Group Ventures'),
(25, 2, 'Dream 11 (gaming platform)', 'Dream 11 Gaming LLC'),
(26, 2, 'Grand Midwest Group', 'Grand Midwest Group'),
(27, 2, 'Panerai', 'Panerai Investments'),
(28, 2, 'LivFast', 'LivFast Medicines'),
(29, 2, 'SoundLogic', 'SoundLogic Electronics Ltd.'),
(30, 2, 'WardWiz', 'WardWiz Limited'),
(31, 3, 'Dabur', 'Dabur Limited'),
(32, 3, 'Cadburys', 'Cadburys International'),
(33, 3, 'Emami', 'Emami Group'),
(34, 3, 'ICICI', 'ICICI Bank'),
(35, 3, 'Nerolac', 'Nerolac Paints'),
(36, 3, 'Zen Mobile', 'Zen Mobile Limited'),
(37, 3, 'Dettol India', 'Dettol India Pvt. Limited'),
(38, 3, 'Syska LED', 'Syska Electronics'),
(39, 3, 'The Muthoot Group', 'The Muthoot Group'),
(40, 3, 'One Plus', 'One Plus Mobiles'),
(41, 4, 'Dollar Club Vests', 'Dollar Clothing Limited'),
(42, 4, 'Levi', 'Levi Jeans'),
(43, 4, 'LG', 'LG Electronics'),
(44, 4, 'Micromax', 'Micromax Mobiles'),
(45, 4, 'Thums Up', 'Parle Beverages'),
(46, 4, 'PC Jewellers', 'PC Jewellers'),
(47, 4, 'Tata Motors', 'Tata Motors Limited'),
(48, 4, 'Tide', 'Procter and Gambel'),
(49, 4, 'Layer’R Shot deo', 'Layer Internationa;'),
(50, 4, 'HUL Ayush', 'Ayush Pharma'),
(51, 4, 'TAFE', 'TAFE International'),
(52, 4, 'Honda Motorcycles', 'Honda Motorcycles Limited'),
(53, 4, 'Prince Pipes', 'Prince Pipes India Limited'),
(54, 4, 'RR Kables', 'RR Kables Limited'),
(55, 4, 'Revital', 'Revital Pharma'),
(56, 4, 'Relaxo Sparx Footwear', 'Bata India Limited'),
(57, 4, 'Fortune Oil', 'Fortune Oil Limited'),
(58, 4, 'Policybazzar.com', 'Policybazzar Online LLC'),
(59, 4, 'Eveready', 'Eveready Batteries'),
(60, 4, 'Liv Guard', 'Liv Guard Limited'),
(61, 4, 'Lodha Developers', 'Lodha Developers Group'),
(62, 5, 'Nokia', 'Nokia Mobiles'),
(63, 5, 'Uber Eats', 'Uber Group'),
(64, 5, 'Caprese', 'Caprese Limited'),
(65, 5, 'Gionee', 'Gionee Mobiles'),
(66, 5, 'Sunfeast Dark Fantasy', 'Sunfeast Buiscuits India'),
(67, 5, 'Star Plus', 'Star Group'),
(68, 5, 'Mango Frooti', 'Parle Beverages'),
(69, 5, 'MakeMyTrip', 'MakeMyTrip Online LLC'),
(70, 5, 'Sunsilk', 'Sunsilk India'),
(71, 5, 'Philips', 'Philips Electronics'),
(72, 5, 'Garnier', 'Garnier Cosmetics Limited'),
(73, 5, 'Maybelline', 'Maybelline International');

-- 
-- Dumping data for table celebrities
--
INSERT INTO celebrities VALUES
(1, 'Deepika Padukone', 33, 'Female'),
(2, 'Mahendra Singh Dhoni', 38, 'Male'),
(3, 'Amitabh Bachchan', 77, 'Male'),
(4, 'Akshay Kumar', 52, 'Male'),
(5, 'Alia Bhatt', 26, 'Female');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;